### ISSUE TITLE
Disable Cipher? Two users have made Cipher deposits into Binance

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/wallet#2066]
Despite binance's large warning that it only accepts Oasis Consensus transfers... users continue to find ways to annoy Binance support team and us to recover their ROSE.

- almost all wallet users should only be selecting Sapphire in the ParaTime tab
- approximately 0 users should be selecting Cipher in the ParaTime tab

Maybe we should just disable Cipher in the dropdown. Or label it "Cipher (experimental)" to scare them.

**Comment by matevz** [comment]
Agree. We can safely assume that Cipher developers can use CLI for deposits. Or, we could hide this behind the "Expert" flag in the Settings (do we have one?).
